#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####

sketchybar --bar position=top height=40 blur_radius=30 color=$BAR_COLOR

##### Default Item Styling #####

default=(
    padding_left=2
    padding_right=2
    background.color="$ITEM_BG_COLOR"
    background.corner_radius=6
    background.height=28
    icon.font="IBM Plex Mono:Bold:17.0"
    icon.font="FiraCode Nerd Font Mono:Bold:14.0"
    icon.color=$WHITE
    icon.y_offset=1
    label.color=$WHITE
    label.y_offset=1
    icon.padding_left=10
    icon.padding_right=4
    label.padding_left=4
    label.padding_right=10
)
sketchybar --default "${default[@]}"

##### Left Items #####

source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"

##### Right Items #####

source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"

##### First Update #####

sketchybar --update

